// Generated by CoffeeScript 1.6.2
/*
 Sticky Elements Shortcut for jQuery Waypoints - v2.0.3
 Copyright (c) 2011-2013 Caleb Troughton
 Dual licensed under the MIT license and GPL license.
 https://github.com/imakewebthings/jquery-waypoints/blob/master/licenses.txt
 */


(function() {
    (function(root, factory) {
        if (typeof define === 'function' && define.amd) {
            return define(['jquery', 'waypoints'], factory);
        } else {
            return factory(root.jQuery);
        }
    })(this, function($) {
        var defaults, wrap;

        defaults = {
            wrapper: '<div class="sticky-wrapper" />',
            stuckClass: 'stuck'
        };
        wrap = function($elements, options) {
            $elements.wrap(options.wrapper);
            return $elements.parent();
        };
        $.waypoints('extendFn', 'sticky', function(opt) {
            var $wrap, options, originalHandler;

            options = $.extend({}, $.fn.waypoint.defaults, defaults, opt);
            $wrap = wrap(this, options);
            originalHandler = options.handler;
            options.handler = function(direction) {
                var $sticky, shouldBeStuck;

                $sticky = $(this).children(':first');
                shouldBeStuck = direction === 'down' || direction === 'right';
                $sticky.toggleClass(options.stuckClass, shouldBeStuck);
                $wrap.height(shouldBeStuck ? $sticky.outerHeight() : '');
                if (originalHandler != null) {
                    return originalHandler.call(this, direction);
                }
            };
            $wrap.waypoint(options);
            return this.data('stuckClass', options.stuckClass);
        });
        return $.waypoints('extendFn', 'unsticky', function() {
            this.parent().waypoint('destroy');
            this.unwrap();
            return this.removeClass(this.data('stuckClass'));
        });
    });

}).call(this);

// start asalah configuration
jQuery(document).ready(function($) {
    var fixed_header_height = $('.site_header').outerHeight(true);
    var sliding_offset = 24 + fixed_header_height;
    $('.blog_social_share.sliding_social_share').waypoint('sticky', {
        offset: sliding_offset // Apply "stuck" when element 30px from top
    });


    jQuery(window).scroll(function() {
        var scrolling = jQuery(window).scrollTop();
        var social_share_height = $('.blog_social_share').outerHeight(true);
        var fixed_header_height = $('.site_header.fixed_header.sticky_header').outerHeight(true);


        var author_box_offset = jQuery('.author_box').offset().top - social_share_height - fixed_header_height - 32;
        if (scrolling > author_box_offset) {
            jQuery('.blog_social_share.sliding_social_share').stop().addClass('absolute');
        } else if (scrolling < author_box_offset) {
            jQuery('.blog_social_share.sliding_social_share').removeClass('absolute');
        }
    });

    jQuery(window).load(function() {
        var scrolling = jQuery(window).scrollTop();
        var social_share_height = $('.blog_social_share.sliding_social_share').outerHeight(true);
        var fixed_header_height = $('.site_header.fixed_header.sticky_header').outerHeight(true);

        var author_box_offset = jQuery('.author_box').offset().top - social_share_height - fixed_header_height - 32;
        if (scrolling > author_box_offset) {
            jQuery('.blog_social_share.sliding_social_share').stop().addClass('absolute');
        } else if (scrolling < author_box_offset) {
            jQuery('.blog_social_share.sliding_social_share').removeClass('absolute');
        }
    });

});